@startuml

left to right direction
skinparam packageStyle rectangle

actor User
actor Admin
actor Attacker

rectangle "ArcadeHaven - Game Management Abuse Case" {

    User --> (Create Order)
    User --> (Add Game to Order)
    User --> (Cancel Pending Order)
    User --> (Finish Order)
    User --> (Activate Game Key)

    Admin --> (Manage User Library Entries)

    Attacker --> (Force Duplicated Purchase)
    Attacker --> (Modify Order)
    Attacker --> (Bypass Payment)
    Attacker --> (Guess Game Key)
    Attacker --> (Privilege Escalation)

    (Create Order) ..> (Authentication Check) : <<include>>

    (Add Game to Order) ..> (Authentication Check) : <<include>>
    (Add Game to Order) ..> (Server-side Validation) : <<include>>

    (Cancel Pending Order) ..> (Authentication Check) : <<include>>
    (Cancel Pending Order) ..> (Server-side Validation) : <<include>>

    (Finish Order) ..> (Authentication Check) : <<include>>
    (Finish Order) ..> (Server-side Validation) : <<include>>
    (Finish Order) ..> (Generate Invoice) : <<include>>
    (Finish Order) ..> (Activate Game Key) : <<include>>
    (Finish Order) ..> (Download Game Key Card) : <<include>>

    (Manage User Library Entries) ..> (Authentication Check) : <<include>>
    (Manage User Library Entries) ..> (Server-side Validation) : <<include>>

    (Activate Game Key) ..> (Add Game to Library) : <<include>>

    (Authentication Check) ..> (Modify Order) : <<mitigates>>

    (Server-side Validation) ..> (Force Duplicated Purchase) : <<mitigates>>
    (Server-side Validation) ..> (Modify Order) : <<mitigates>>
    (Server-side Validation) ..> (Bypass Payment) : <<mitigates>>

    (Force Duplicated Purchase) ..> (Add Game to Library) : <<threatens>>

    (Bypass Payment) ..> (Finish Order) : <<threatens>>
    (Guess Game Key) ..> (Activate Game Key) : <<threatens>>

    (Privilege Escalation) ..> (Manage User Library Entries) : <<threatens>>
}

@enduml