#spring.application.name=arcadehaven
spring.datasource.url=jdbc:postgresql://vsgate-s1.dei.isep.ipp.pt:10345/
spring.datasource.username=postgres
spring.datasource.password=LQ4QGqhh8gtS
spring.datasource.driver-class-name=org.postgresql.Driver