#spring.application.name=arcadehaven
spring.datasource.url=jdbc:postgresql://vsgate-s1.dei.isep.ipp.pt:10345/
spring.datasource.username=postgres
spring.datasource.password=LQ4QGqhh8gtS
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANT: PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Evita problemas com LOBs
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===============================
# PERFORMANCE / LAZY LOADING
# ===============================
spring.jpa.open-in-view=false