@startuml

left to right direction
skinparam packageStyle rectangle

actor Attacker
actor Administrator

rectangle "ArcadeHaven - Role Management Abuse Case" {

  Administrator --> (Manage User Activation)
  Administrator --> (Change User Role)

  Attacker --> (Privilege Escalation)
  Attacker --> (JWT Token Theft)

  (Change User Role) ..> (RBAC Validation) : <<include>>
  (Change User Role) ..> (Endpoint Authentication) : <<include>>

  (Manage User Activation) ..> (RBAC Validation) : <<include>>
  (Manage User Activation) ..> (Endpoint Authentication) : <<include>>

  (RBAC Validation) ..> (Privilege Escalation) : <<mitigates>>
  (Endpoint Authentication) ..> (JWT Token Theft) : <<mitigates>>

  (Privilege Escalation) ..> (Change User Role) : <<threatens>>
  (Privilege Escalation) ..> (Manage User Activation) : <<threatens>>

  (JWT Token Theft) ..> (Endpoint Authentication) : <<threatens>>
  (JWT Token Theft) ..> (RBAC Validation) : <<threatens>>

}

@enduml