@startuml

left to right direction
skinparam packageStyle rectangle

actor User
actor Attacker

rectangle "ArcadeHaven - Authentication Abuse Case" {

  User --> (Register)
  User --> (Login)

  Attacker --> (Inject Malicious Code)
  Attacker --> (Hijack Account)
  Attacker --> (Brute Force Login)
  Attacker --> (Dictionary Attack)
  Attacker --> (JWT Token Theft)

  (Register) ..> (Input Sanitization) : <<includes>>

  (Login) ..> (Input Sanitization) : <<includes>>
  (Login) ..> (MFA) : <<includes>>
  (Login) ..> (Lock account after 5 tries) : <<includes>>

  (Input Sanitization) ..> (Inject Malicious Code) : <<mitigates>>

  (MFA) ..> (Hijack Account) : <<mitigates>>
  (MFA) ..> (Brute Force Login) : <<mitigates>>
  (MFA) ..> (Dictionary Attack) : <<mitigates>>

  (Lock account after 5 tries) ..> (Brute Force Login) : <<mitigates>>

  (JWT Token Theft) ..> (Login) : <<threatens>>

}

@enduml