name: Docker Build, Scan & DAST # Dynamic Application Security Testing (DAST)

on:
  workflow_call:

  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:

  build-and-scan:
    name: Docker Build, Scan and DAST
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Api

    env:
      SPRING_DATASOURCE_URL: ${{ vars.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

      KEYCLOAK_JWK_SET_URI: ${{ vars.KEYCLOAK_JWK_SET_URI }}
      KEYCLOAK_SERVER_URL: ${{ vars.KEYCLOAK_SERVER_URL }}
      KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
      KEYCLOAK_CLIENT_ID: ${{ vars.KEYCLOAK_CLIENT_ID }}
      KEYCLOAK_ADMIN_USERNAME: ${{ secrets.KEYCLOAK_ADMIN_USERNAME }}
      KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}

      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

      SFTP_HOST: ${{ vars.SFTP_HOST }}
      SFTP_PORT: ${{ vars.SFTP_PORT }}
      SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
      SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      SFTP_REMOTE_DIR: ${{ vars.SFTP_REMOTE_DIR }}

      KC_DB: ${{ vars.KC_DB }}
      KC_DB_URL: ${{ vars.KC_DB_URL }}
      KC_DB_USERNAME: ${{ secrets.POSTGRES_USER }}
      KC_DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      KC_HOSTNAME_STRICT: ${{ vars.KC_HOSTNAME_STRICT }}
      KC_HTTP_ENABLED: ${{ vars.KC_HTTP_ENABLED }}
      KC_HEALTH_ENABLED: ${{ vars.KC_HEALTH_ENABLED }}

      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v5

      # Set up Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Create reports directory in workspace if it do
      - name: Create reports directory
        run: mkdir -p reports

      # Build Docker image
      - name: Build images
        run: docker compose build

      # Installs Docker Scout as a plugin
      - name: Install Docker Scout
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh

      # Login to Docker Hub using PAT
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # Scan Docker image for known vulnerabilities (CVEs) using Docker Scout
      - name: Docker Scout CVE scan
        run: |
          IMAGE=arcadehaven-api:latest
          docker scout cves $IMAGE

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO- https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # Run Trivy scan - Tool used to find vulnerabilities and dependency issues in the built Docker image and generates a JSON report
      - name: Scan Docker image with Trivy
        run: |
          IMAGE=arcadehaven-api:latest
          trivy image --format json --output Api/reports/trivy-report.json $IMAGE

      # Upload Trivy report
      - name: Upload Trivy report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: Api/reports/trivy-report.json

      # Start docker containers
      - name: Start containers
        run: docker compose up -d

      # Keycloak health check
      - name: Wait for Keycloak
        run: |
          for i in {1..60}; do
            if curl -fs http://localhost:8180/realms/arcadehaven/.well-known/openid-configuration; then
              echo "Keycloak ready"
              exit 0
            fi

            echo $i ": Waiting for Keycloak..."
            sleep 5
          done

          echo "Keycloak failed"
          docker compose logs

          exit 1

      # Application health check
      - name: Wait for app
        run: |
          for i in {1..60}; do
            if curl -fs http://localhost:8080/actuator/health; then
              echo "App ready"
              exit 0
            fi

            echo $i ": Waiting for app..."
            sleep 5
          done

          echo "App failed to start"
          docker compose logs

          exit 1

      # Run OWASP ZAP DAST scan
      - name: OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "http://localhost:8080"
          fail_action: false
          allow_issue_writing: false
          artifact_name: zap-report
          report_html: Api/reports/zap-report.html

      - name: OWASP ZAP API Scan (OpenAPI)
        uses: zaproxy/action-api-scan@v0.8.0
        with:
          target: "http://localhost:8080/v3/api-docs"

      - name: Upload all reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: Api/reports/

      - name: Cleanup
        if: always()
        run: docker compose down