name: DAST - OWASP ZAP # Dynamic Application Security Testing (DAST)

on:
  push:
    branches: [ main, pipeline ]

  pull_request:
    branches: [ main, pipeline ]

# Read repo, write to security tab in github and read github actions
permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  zap:
    name: OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Api

    steps:
      # Get code from repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # Install Java for GitHub runner
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      # Gives execution permissions to Maven wrapper
      - name: Fix Maven wrapper permissions
        run: chmod +x ./mvnw

      # Build application before running security scan
      - name: Build project
        run: ./mvnw -B clean package -DskipTests

      # Start Spring Boot application in background
      - name: Start application
        run: |
          nohup ./mvnw spring-boot:run > app.log 2>&1 &

      # Wait until application is ready
      - name: Wait for application
        run: |
          for i in {1..30}; do
            curl -s http://localhost:8080/actuator/health && break
            echo "Waiting for app..."
            sleep 5
          done

      # Runs OWASP ZAP baseline scan against running application
      - name: OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "http://localhost:8080/actuator/health"
          fail_action: false
          allow_issue_writing: false
          artifact_name: zap-report

      # Uploads ZAP HTML report as workflow artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html