name: CI Pipeline

on:
  push:
    branches: [main, pipeline]
  pull_request:
    branches: [main, pipeline]

  workflow_dispatch:

jobs:
  secret-scanning:
    uses: ./.github/workflows/secret-scanning.yml

  build:
    needs: secret-scanning
    uses: ./.github/workflows/build.yml

  sast-codeql:
    needs: build
    uses: ./.github/workflows/sast-codeql.yml

  code-quality:
    needs: build
    uses: ./.github/workflows/sast-code-quality.yml

  sca-dependency-check:
    needs: build
    uses: ./.github/workflows/sca-dependency-check.yml

  docker-dast:
    needs: [sast-codeql, code-quality, sca-dependency-check]
    uses: ./.github/workflows/build-docker-and-dast.yml

  security-tests:
    needs: docker-dast
    uses: ./.github/workflows/security-and-smoke-tests.yml