name: SAST - Code Quality

on:
  workflow_call:

  workflow_dispatch:

# Read repository
permissions:
  contents: read

jobs:
  code-quality:
    name: Code Quality and Code Smells
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Api

    steps:
      # Get repository from github
      - name: Checkout repository
        uses: actions/checkout@v5

      # Install Java for GitHub runner
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      # Gives execution permissions to Maven wrapper
      - name: Fix Maven wrapper permissions
        run: chmod +x ./mvnw

      # Create reports directory in workspace if it doesn't exist
      - name: Create reports directory
        run: mkdir -p reports/code-quality

      # Runs Checkstyle static code analysis (formatting issues, naming issues and bad code style)
      - name: Run Checkstyle (generate report)
        run: ./mvnw -B checkstyle:checkstyle

      - name: Move Checkstyle report
        if: always()
        run: |
          mkdir -p reports/code-quality
          run: mv target/checkstyle-result.xml reports/code-quality/ || true

      # Runs SpotBugs static analysis (potential bugs, unsafe code and code smells)
      - name: Run SpotBugs
        run: ./mvnw -B spotbugs:spotbugs
 
      - name: Upload code quality reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-code-quality
          path: Api/reports/