name: SCA - Dependency Check # Software Composition Analysis (SCA)

on:
  workflow_call:

  workflow_dispatch:

# Reads repository
permissions:
  contents: read

jobs:
  sca:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Api

    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

    steps:
      # Get repository from github
      - name: Checkout repository
        uses: actions/checkout@v5

      # Install Java for GitHub Runner
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      # Create reports directory in workspace if it doesn't exist
      - name: Create reports directory
        run: mkdir -p reports/sca

      # Gives execution permissions to Maven wrapper
      - name: Fix Maven wrapper permissions
        run: chmod +x ./mvnw

      # Cache OWASP Dependency Check database
      - name: Cache Dependency Check data
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: dependency-check-data

      # Runs OWASP dependency vulnerability scan
      - name: Run OWASP Dependency Check
        run: ./mvnw -B org.owasp:dependency-check-maven:check -DossindexAnalyzerEnabled=false
        env:
          NVD_API_KEY: ${{ env.NVD_API_KEY }}

      - name: Move Dependency Check report
        if: always()
        run: mv target/dependency-check-report.html reports/sca/ || true
 
      - name: Upload SCA reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-sca
          path: Api/reports/