name: Secret Scanning

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

# Permissions to read repository
permissions:
  contents: read

jobs:
  secret-scan:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      # Gets repository from github
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Marks repository as safe for git operations
      - name: Configure Git safe directory
        run: git config --global --add safe.directory /github/workspace

      # Runs Gitleaks to verify for secrets/keys leaks
      - name: Run Gitleaks
        uses: docker://zricethezav/gitleaks:latest
        with:
          args: detect --source=. --verbose --redact