name: Secret Scanning

on:
  push:
    branches: [ main, pipeline ]

  pull_request:
    branches: [ main, pipeline ]

  workflow_dispatch:

# Permissions to read repository
permissions:
  contents: read

jobs:
  secret-scan:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      # Gets repository from github
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create reports directory
        run: mkdir -p Api/reports/secrets

      # Runs Gitleaks to verify for secrets/keys leaks in current files
      - name: Run Gitleaks (generate report)
        uses: docker://zricethezav/gitleaks:latest
        with:
          args: >
            dir .
            --config=.gitleaks.toml
            --report-format json
            --report-path Api/reports/secrets/gitleaks-report.json
            --redact

      # Upload results to reports folder
      - name: Upload secret scan report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: secret-scan-report
          path: Api/reports/secrets/